"""
src/clients/mcp_client.py
──────────────────────────
Async MCP client that connects to the Zerodha Kite MCP server
(hosted at https://mcp.kite.trade/mcp or a self-hosted instance).

The hosted server uses OAuth-based Kite login – no API key is required
from the client side; the user authenticates via a browser redirect URL
generated by the `login` tool.

Usage:
    async with KiteMCPClient() as client:
        holdings = await client.get_holdings()
"""

from __future__ import annotations

import json
import logging
import os
import sqlite3
import time
from typing import Any

import httpx

from config.settings import settings
from src.commands.base import CommandRunner

logger = logging.getLogger(__name__)


class KiteMCPClient:
    """
    Thin async HTTP client for the Zerodha Kite MCP server.

    The MCP server exposes a JSON-RPC 2.0-compatible HTTP endpoint.
    We use the 'tools/call' method to invoke MCP tools.
    """

    # Session key/value store persists across restarts / new client instances.
    # Lives under settings.output_dir (bind-mounted into the container at
    # /app/output) rather than /tmp, so a login done in one `mosaic.sh kite`
    # run survives into a later `mosaic.sh analyze` run's fresh --rm container.
    # SQLite (not a flat JSON file) — same convention as output/.cache/llm_cache.db.
    _DB_PATH = os.path.join(settings.output_dir, ".cache", "kite_mcp_session.db")

    # Two distinct keys: the MCP protocol session (from the `initialize`
    # handshake) and the legacy Kite OAuth cookie are unrelated identifiers —
    # storing them under one shared slot let one silently clobber the other.
    _MCP_SESSION_KEY = "mcp_session_id"
    _KITE_COOKIE_KEY = "kite_cookie_session_id"

    @classmethod
    def _conn(cls) -> sqlite3.Connection:
        os.makedirs(os.path.dirname(cls._DB_PATH), exist_ok=True)
        conn = sqlite3.connect(cls._DB_PATH)
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute(
            "CREATE TABLE IF NOT EXISTS kite_session ("
            "key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at REAL NOT NULL)"
        )
        return conn

    @classmethod
    def _load_session(cls, key: str) -> str | None:
        """Load a persisted session value from SQLite."""
        try:
            with cls._conn() as conn:
                row = conn.execute(
                    "SELECT value FROM kite_session WHERE key = ?", (key,)
                ).fetchone()
                return row[0] if row else None
        except Exception:
            return None

    @classmethod
    def _save_session(cls, key: str, value: str) -> None:
        """Persist a session value to SQLite for reuse across instances/restarts."""
        try:
            with cls._conn() as conn:
                conn.execute(
                    "INSERT OR REPLACE INTO kite_session (key, value, updated_at) VALUES (?, ?, ?)",
                    (key, value, time.time()),
                )
        except Exception:
            pass

    @classmethod
    def _clear_session(cls, key: str) -> None:
        """Remove a persisted session value."""
        try:
            with cls._conn() as conn:
                conn.execute("DELETE FROM kite_session WHERE key = ?", (key,))
        except Exception:
            pass

    def __init__(self) -> None:
        # [NON-SENSITIVE] MCP endpoint URL (from config)
        self._base_url: str = settings.kite_mcp_url.rstrip("/")
        self._timeout: int = settings.kite_mcp_timeout
        self._client: httpx.AsyncClient | None = None
        self._session_id: str | None = self._load_session(self._KITE_COOKIE_KEY)   # Kite OAuth session (legacy cookie)
        self._mcp_session_id: str | None = self._load_session(self._MCP_SESSION_KEY)  # MCP protocol session ID
        self._runner = CommandRunner(max_retries=3)

    # ── Context Manager ───────────────────────────────────────────────────────

    async def __aenter__(self) -> "KiteMCPClient":
        self._client = httpx.AsyncClient(
            timeout=self._timeout,
            headers={"Content-Type": "application/json"},
        )
        logger.info("KiteMCPClient connected to %s", self._base_url)
        # Reuse persisted session if available — re-initialising would create a
        # NEW unauthenticated session, discarding the one the user logged into.
        if not self._mcp_session_id:
            await self._mcp_initialize()
        else:
            logger.info(
                "KiteMCPClient: reusing persisted mcp-session-id (%s…)",
                self._mcp_session_id[:12],
            )
        return self

    async def _mcp_initialize(self) -> None:
        """
        Perform the MCP protocol handshake.

        The Kite MCP server (mcp.kite.trade v0.3.1) requires:
          1. POST initialize  → server returns mcp-session-id in response headers
          2. POST notifications/initialized (with Mcp-Session-Id header)
        All subsequent tool calls must carry this Mcp-Session-Id header.
        """
        if self._client is None:
            return
        try:
            r = await self._client.post(
                self._base_url,
                json={
                    "jsonrpc": "2.0",
                    "id": 0,
                    "method": "initialize",
                    "params": {
                        "protocolVersion": "2024-11-05",
                        "capabilities": {},
                        "clientInfo": {"name": "mosaic-agent", "version": "1.0"},
                    },
                },
            )
            sid = r.headers.get("mcp-session-id")
            if sid:
                self._mcp_session_id = sid
                self._save_session(self._MCP_SESSION_KEY, sid)
                logger.info("KiteMCPClient: mcp-session-id established (%s…)", sid[:12])
            # Send initialized notification to complete handshake
            if self._mcp_session_id:
                await self._client.post(
                    self._base_url,
                    json={"jsonrpc": "2.0", "method": "notifications/initialized"},
                    headers={"Mcp-Session-Id": self._mcp_session_id},
                )
        except Exception as exc:
            logger.warning("KiteMCPClient: MCP initialize failed: %s", exc)

    async def __aexit__(self, *_: Any) -> None:
        if self._client:
            await self._client.aclose()
            logger.info("KiteMCPClient connection closed")

    # ── Low-level MCP call ────────────────────────────────────────────────────

    async def _call_tool(self, tool_name: str, arguments: dict[str, Any] | None = None) -> Any:
        """
        Invoke a named MCP tool via JSON-RPC 2.0.

        Args:
            tool_name:  Name of the MCP tool (e.g. "get_holdings").
            arguments:  Optional dict of tool arguments.

        Returns:
            Parsed JSON result from the MCP server.
        """
        if self._client is None:
            raise RuntimeError("KiteMCPClient must be used as an async context manager.")

        payload = {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {
                "name": tool_name,
                "arguments": arguments or {},
            },
        }

        # Every call must carry the MCP protocol session ID as a header.
        headers = {}
        if self._mcp_session_id:
            headers["Mcp-Session-Id"] = self._mcp_session_id
        # Also send legacy Kite session cookie if captured from OAuth callback.
        if self._session_id:
            headers["Cookie"] = f"session_id={self._session_id}"

        logger.debug("MCP call → tool=%s args=%s", tool_name, arguments)

        response = await self._client.post(
            self._base_url,
            json=payload,
            headers=headers,
        )
        if response.status_code == 400:
            body = response.text[:200]
            if tool_name != "login":
                # Kite OAuth session expired — clear and prompt re-login.
                self._session_id = None
                self._clear_session(self._KITE_COOKIE_KEY)
                raise RuntimeError(
                    "Kite session expired. Run: initiate_kite_login() → "
                    "open the URL in your browser → retry."
                )
            # login itself returning 400 means MCP session gone — fall through
            logger.warning("KiteMCPClient: login 400 (%s) — MCP session may be stale", body[:80])
        response.raise_for_status()

        data = response.json()

        # Capture Set-Cookie from Kite login if present — persist to disk
        if "set-cookie" in response.headers:
            cookie = response.headers["set-cookie"]
            if "session_id=" in cookie:
                self._session_id = cookie.split("session_id=")[1].split(";")[0]
                self._save_session(self._KITE_COOKIE_KEY, self._session_id)
                logger.info("KiteMCPClient: session_id captured and persisted")

        if "error" in data:
            raise RuntimeError(
                f"MCP tool '{tool_name}' returned error: {data['error']}"
            )

        result = data.get("result", {})

        # MCP tools/call wraps content in a list of content blocks
        if isinstance(result, dict) and "content" in result:
            content_blocks = result["content"]
            if content_blocks and isinstance(content_blocks, list):
                text = content_blocks[0].get("text", "")
                try:
                    return json.loads(text)
                except (json.JSONDecodeError, TypeError):
                    return text

        return result

    # ── Authentication ────────────────────────────────────────────────────────

    async def login(self) -> str:
        """
        Initiates Kite login via the MCP 'login' tool.

        Returns:
            Authorization URL that the user must open in a browser to authenticate.
        """
        import re
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "login", {})
        result = await self._runner.run_async(cmd)

        if isinstance(result, dict):
            for key in ("url", "login_url", "authorization_url", "auth_url", "redirect_url"):
                value = result.get(key)
                if value:
                    return str(value)
            text = str(result)
        else:
            text = str(result)

        # The hosted MCP server's "login" tool returns free-form instructional
        # prose for an LLM agent to parse (AI-risk disclaimer + a markdown
        # link), not a clean JSON URL field — pull the URL out of it directly.
        # `[^\s)\]]+` stops before a markdown link's closing ')' so the match
        # doesn't swallow trailing punctuation.
        match = re.search(r"https?://[^\s)\]]+", text)
        if match:
            return match.group(0)

        logger.warning("KiteMCPClient.login(): could not find a URL in response: %s", text[:200])
        return text

    # ── Portfolio Tools ───────────────────────────────────────────────────────

    async def get_profile(self) -> dict[str, Any]:
        """Fetch the authenticated user's Kite profile."""
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_profile", {})
        return await self._runner.run_async(cmd)

    async def get_holdings(self) -> list[dict[str, Any]]:
        """
        Fetch all portfolio holdings (long-term / CNC positions).

        Returns:
            List of holding dicts as returned by Kite API.
        """
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_holdings", {})
        result = await self._runner.run_async(cmd, retryable=True)
        if isinstance(result, list):
            return result
        # Some MCP server versions wrap the list
        if isinstance(result, dict) and "holdings" in result:
            return result["holdings"]
        return []

    async def get_positions(self) -> dict[str, Any]:
        """
        Fetch current open positions (intraday + short-term).

        Returns:
            Dict with 'net' and 'day' position lists.
        """
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_positions", {})
        return await self._runner.run_async(cmd)

    async def get_margins(self) -> dict[str, Any]:
        """Fetch account margin details (equity + commodity)."""
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_margins", {})
        return await self._runner.run_async(cmd)

    async def get_quotes(self, instruments: list[str]) -> dict[str, Any]:
        """
        Fetch last-traded quotes for a list of instruments.

        Args:
            instruments: List of 'EXCHANGE:SYMBOL' strings e.g. ['NSE:RELIANCE', 'NSE:TCS']
        """
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_quotes", {"instruments": instruments})
        return await self._runner.run_async(cmd)

    async def get_ltp(self, instruments: list[str]) -> dict[str, Any]:
        """Fetch last traded price only (lighter than full quotes)."""
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_ltp", {"instruments": instruments})
        return await self._runner.run_async(cmd)


async def fetch_authenticated_profile(client: "KiteMCPClient") -> dict[str, Any]:
    """
    Fetch the Kite profile, transparently handling the login flow if needed.

    The MCP server sometimes returns 200 OK with a plain-text "not logged in"
    body instead of raising, so a non-dict response is treated the same as
    an auth failure. Prints the OAuth URL and blocks on input() for the user
    to complete browser login, then retries once.

    Shared by the `kite` CLI command, the `/kite` chat command, and the
    portfolio sync service — all three need identical login-detection and
    retry behaviour.
    """
    async def _fetch() -> dict[str, Any]:
        result = await client.get_profile()
        if not isinstance(result, dict):
            raise RuntimeError(f"Kite login required: {result}")
        return result

    try:
        return await _fetch()
    except Exception as exc:
        exc_lower = str(exc).lower()
        if "401" in str(exc) or "unauthorized" in exc_lower or "login" in exc_lower or "logged in" in exc_lower:
            login_url = await client.login()
            print(
                "\nKite login required. Copy the link below and open it in your "
                f"browser to authenticate:\n{login_url}\n"
            )
            input("Press ENTER after completing authentication in the browser...")
            return await _fetch()
        raise
