"""
src/clients/mcp_client.py
──────────────────────────
Async MCP client that connects to the Zerodha Kite MCP server
(hosted at https://mcp.kite.trade/mcp or a self-hosted instance).

The hosted server uses OAuth-based Kite login – no API key is required
from the client side; the user authenticates via a browser redirect URL
generated by the `login` tool.

Usage:
    async with KiteMCPClient() as client:
        holdings = await client.get_holdings()
"""

from __future__ import annotations

import json
import logging
from typing import Any

import httpx

from config.settings import settings

logger = logging.getLogger(__name__)


class KiteMCPClient:
    """
    Thin async HTTP client for the Zerodha Kite MCP server.

    The MCP server exposes a JSON-RPC 2.0-compatible HTTP endpoint.
    We use the 'tools/call' method to invoke MCP tools.
    """

    def __init__(self) -> None:
        # [NON-SENSITIVE] MCP endpoint URL (from config)
        self._base_url: str = settings.kite_mcp_url.rstrip("/")
        self._timeout: int = settings.kite_mcp_timeout
        self._client: httpx.AsyncClient | None = None
        self._session_id: str | None = None

    # ── Context Manager ───────────────────────────────────────────────────────

    async def __aenter__(self) -> "KiteMCPClient":
        self._client = httpx.AsyncClient(
            timeout=self._timeout,
            headers={"Content-Type": "application/json"},
        )
        logger.info("KiteMCPClient connected to %s", self._base_url)
        return self

    async def __aexit__(self, *_: Any) -> None:
        if self._client:
            await self._client.aclose()
            logger.info("KiteMCPClient connection closed")

    # ── Low-level MCP call ────────────────────────────────────────────────────

    async def _call_tool(self, tool_name: str, arguments: dict[str, Any] | None = None) -> Any:
        """
        Invoke a named MCP tool via JSON-RPC 2.0.

        Args:
            tool_name:  Name of the MCP tool (e.g. "get_holdings").
            arguments:  Optional dict of tool arguments.

        Returns:
            Parsed JSON result from the MCP server.
        """
        if self._client is None:
            raise RuntimeError("KiteMCPClient must be used as an async context manager.")

        payload = {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {
                "name": tool_name,
                "arguments": arguments or {},
            },
        }

        # Attach session cookie if we have one from a previous login
        headers = {}
        if self._session_id:
            headers["Cookie"] = f"session_id={self._session_id}"

        logger.debug("MCP call → tool=%s args=%s", tool_name, arguments)

        response = await self._client.post(
            self._base_url,
            json=payload,
            headers=headers,
        )
        response.raise_for_status()

        data = response.json()

        # Capture Set-Cookie from Kite login if present
        if "set-cookie" in response.headers:
            cookie = response.headers["set-cookie"]
            if "session_id=" in cookie:
                self._session_id = cookie.split("session_id=")[1].split(";")[0]
                logger.debug("MCP session_id captured")

        if "error" in data:
            raise RuntimeError(
                f"MCP tool '{tool_name}' returned error: {data['error']}"
            )

        result = data.get("result", {})

        # MCP tools/call wraps content in a list of content blocks
        if isinstance(result, dict) and "content" in result:
            content_blocks = result["content"]
            if content_blocks and isinstance(content_blocks, list):
                text = content_blocks[0].get("text", "")
                try:
                    return json.loads(text)
                except (json.JSONDecodeError, TypeError):
                    return text

        return result

    # ── Authentication ────────────────────────────────────────────────────────

    async def login(self) -> str:
        """
        Initiates Kite login via the MCP 'login' tool.

        Returns:
            Authorization URL that the user must open in a browser to authenticate.
        """
        result = await self._call_tool("login")
        if isinstance(result, dict):
            return result.get("url", str(result))
        return str(result)

    # ── Portfolio Tools ───────────────────────────────────────────────────────

    async def get_profile(self) -> dict[str, Any]:
        """Fetch the authenticated user's Kite profile."""
        return await self._call_tool("get_profile")

    async def get_holdings(self) -> list[dict[str, Any]]:
        """
        Fetch all portfolio holdings (long-term / CNC positions).

        Returns:
            List of holding dicts as returned by Kite API.
        """
        result = await self._call_tool("get_holdings")
        if isinstance(result, list):
            return result
        # Some MCP server versions wrap the list
        if isinstance(result, dict) and "holdings" in result:
            return result["holdings"]
        return []

    async def get_positions(self) -> dict[str, Any]:
        """
        Fetch current open positions (intraday + short-term).

        Returns:
            Dict with 'net' and 'day' position lists.
        """
        return await self._call_tool("get_positions")

    async def get_margins(self) -> dict[str, Any]:
        """Fetch account margin details (equity + commodity)."""
        return await self._call_tool("get_margins")

    async def get_quotes(self, instruments: list[str]) -> dict[str, Any]:
        """
        Fetch last-traded quotes for a list of instruments.

        Args:
            instruments: List of 'EXCHANGE:SYMBOL' strings e.g. ['NSE:RELIANCE', 'NSE:TCS']
        """
        return await self._call_tool("get_quotes", {"instruments": instruments})

    async def get_ltp(self, instruments: list[str]) -> dict[str, Any]:
        """Fetch last traded price only (lighter than full quotes)."""
        return await self._call_tool("get_ltp", {"instruments": instruments})
