"""
src/clients/mcp_client.py
──────────────────────────
Async MCP client that connects to the Zerodha Kite MCP server
(hosted at https://mcp.kite.trade/mcp or a self-hosted instance).

The hosted server uses OAuth-based Kite login – no API key is required
from the client side; the user authenticates via a browser redirect URL
generated by the `login` tool.

Usage:
    async with KiteMCPClient() as client:
        holdings = await client.get_holdings()
"""

from __future__ import annotations

import json
import logging
from typing import Any

import httpx

from config.settings import settings
from src.commands.base import CommandRunner

logger = logging.getLogger(__name__)


class KiteMCPClient:
    """
    Thin async HTTP client for the Zerodha Kite MCP server.

    The MCP server exposes a JSON-RPC 2.0-compatible HTTP endpoint.
    We use the 'tools/call' method to invoke MCP tools.
    """

    # Session file persists the session_id across restarts / new client instances.
    _SESSION_FILE = "/tmp/.kite_mcp_session"

    @classmethod
    def _load_session(cls) -> str | None:
        """Load persisted session_id from disk."""
        import os, json as _json
        try:
            if os.path.exists(cls._SESSION_FILE):
                data = _json.loads(open(cls._SESSION_FILE).read())
                return data.get("session_id")
        except Exception:
            pass
        return None

    @classmethod
    def _save_session(cls, session_id: str) -> None:
        """Persist session_id to disk for reuse across instances."""
        import json as _json
        try:
            open(cls._SESSION_FILE, "w").write(_json.dumps({"session_id": session_id}))
        except Exception:
            pass

    @classmethod
    def _clear_session(cls) -> None:
        """Remove stale session file."""
        import os
        try:
            os.remove(cls._SESSION_FILE)
        except FileNotFoundError:
            pass

    def __init__(self) -> None:
        # [NON-SENSITIVE] MCP endpoint URL (from config)
        self._base_url: str = settings.kite_mcp_url.rstrip("/")
        self._timeout: int = settings.kite_mcp_timeout
        self._client: httpx.AsyncClient | None = None
        self._session_id: str | None = self._load_session()   # Kite OAuth session (legacy cookie)
        self._mcp_session_id: str | None = self._load_session()  # MCP protocol session ID
        self._runner = CommandRunner(max_retries=3)

    # ── Context Manager ───────────────────────────────────────────────────────

    async def __aenter__(self) -> "KiteMCPClient":
        self._client = httpx.AsyncClient(
            timeout=self._timeout,
            headers={"Content-Type": "application/json"},
        )
        logger.info("KiteMCPClient connected to %s", self._base_url)
        # Reuse persisted session if available — re-initialising would create a
        # NEW unauthenticated session, discarding the one the user logged into.
        if not self._mcp_session_id:
            await self._mcp_initialize()
        else:
            logger.info(
                "KiteMCPClient: reusing persisted mcp-session-id (%s…)",
                self._mcp_session_id[:12],
            )
        return self

    async def _mcp_initialize(self) -> None:
        """
        Perform the MCP protocol handshake.

        The Kite MCP server (mcp.kite.trade v0.3.1) requires:
          1. POST initialize  → server returns mcp-session-id in response headers
          2. POST notifications/initialized (with Mcp-Session-Id header)
        All subsequent tool calls must carry this Mcp-Session-Id header.
        """
        if self._client is None:
            return
        try:
            r = await self._client.post(
                self._base_url,
                json={
                    "jsonrpc": "2.0",
                    "id": 0,
                    "method": "initialize",
                    "params": {
                        "protocolVersion": "2024-11-05",
                        "capabilities": {},
                        "clientInfo": {"name": "mosaic-agent", "version": "1.0"},
                    },
                },
            )
            sid = r.headers.get("mcp-session-id")
            if sid:
                self._mcp_session_id = sid
                self._save_session(sid)
                logger.info("KiteMCPClient: mcp-session-id established (%s…)", sid[:12])
            # Send initialized notification to complete handshake
            if self._mcp_session_id:
                await self._client.post(
                    self._base_url,
                    json={"jsonrpc": "2.0", "method": "notifications/initialized"},
                    headers={"Mcp-Session-Id": self._mcp_session_id},
                )
        except Exception as exc:
            logger.warning("KiteMCPClient: MCP initialize failed: %s", exc)

    async def __aexit__(self, *_: Any) -> None:
        if self._client:
            await self._client.aclose()
            logger.info("KiteMCPClient connection closed")

    # ── Low-level MCP call ────────────────────────────────────────────────────

    async def _call_tool(self, tool_name: str, arguments: dict[str, Any] | None = None) -> Any:
        """
        Invoke a named MCP tool via JSON-RPC 2.0.

        Args:
            tool_name:  Name of the MCP tool (e.g. "get_holdings").
            arguments:  Optional dict of tool arguments.

        Returns:
            Parsed JSON result from the MCP server.
        """
        if self._client is None:
            raise RuntimeError("KiteMCPClient must be used as an async context manager.")

        payload = {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {
                "name": tool_name,
                "arguments": arguments or {},
            },
        }

        # Every call must carry the MCP protocol session ID as a header.
        headers = {}
        if self._mcp_session_id:
            headers["Mcp-Session-Id"] = self._mcp_session_id
        # Also send legacy Kite session cookie if captured from OAuth callback.
        if self._session_id:
            headers["Cookie"] = f"session_id={self._session_id}"

        logger.debug("MCP call → tool=%s args=%s", tool_name, arguments)

        response = await self._client.post(
            self._base_url,
            json=payload,
            headers=headers,
        )
        if response.status_code == 400:
            body = response.text[:200]
            if tool_name != "login":
                # Kite OAuth session expired — clear and prompt re-login.
                self._session_id = None
                self._clear_session()
                raise RuntimeError(
                    "Kite session expired. Run: initiate_kite_login() → "
                    "open the URL in your browser → retry."
                )
            # login itself returning 400 means MCP session gone — fall through
            logger.warning("KiteMCPClient: login 400 (%s) — MCP session may be stale", body[:80])
        response.raise_for_status()

        data = response.json()

        # Capture Set-Cookie from Kite login if present — persist to disk
        if "set-cookie" in response.headers:
            cookie = response.headers["set-cookie"]
            if "session_id=" in cookie:
                self._session_id = cookie.split("session_id=")[1].split(";")[0]
                self._save_session(self._session_id)
                logger.info("KiteMCPClient: session_id captured and persisted")

        if "error" in data:
            raise RuntimeError(
                f"MCP tool '{tool_name}' returned error: {data['error']}"
            )

        result = data.get("result", {})

        # MCP tools/call wraps content in a list of content blocks
        if isinstance(result, dict) and "content" in result:
            content_blocks = result["content"]
            if content_blocks and isinstance(content_blocks, list):
                text = content_blocks[0].get("text", "")
                try:
                    return json.loads(text)
                except (json.JSONDecodeError, TypeError):
                    return text

        return result

    # ── Authentication ────────────────────────────────────────────────────────

    async def login(self) -> str:
        """
        Initiates Kite login via the MCP 'login' tool.

        Returns:
            Authorization URL that the user must open in a browser to authenticate.
        """
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "login", {})
        result = await self._runner.run_async(cmd)
        if isinstance(result, dict):
            return result.get("url", str(result))
        return str(result)

    # ── Portfolio Tools ───────────────────────────────────────────────────────

    async def get_profile(self) -> dict[str, Any]:
        """Fetch the authenticated user's Kite profile."""
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_profile", {})
        return await self._runner.run_async(cmd)

    async def get_holdings(self) -> list[dict[str, Any]]:
        """
        Fetch all portfolio holdings (long-term / CNC positions).

        Returns:
            List of holding dicts as returned by Kite API.
        """
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_holdings", {})
        result = await self._runner.run_async(cmd, retryable=True)
        if isinstance(result, list):
            return result
        # Some MCP server versions wrap the list
        if isinstance(result, dict) and "holdings" in result:
            return result["holdings"]
        return []

    async def get_positions(self) -> dict[str, Any]:
        """
        Fetch current open positions (intraday + short-term).

        Returns:
            Dict with 'net' and 'day' position lists.
        """
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_positions", {})
        return await self._runner.run_async(cmd)

    async def get_margins(self) -> dict[str, Any]:
        """Fetch account margin details (equity + commodity)."""
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_margins", {})
        return await self._runner.run_async(cmd)

    async def get_quotes(self, instruments: list[str]) -> dict[str, Any]:
        """
        Fetch last-traded quotes for a list of instruments.

        Args:
            instruments: List of 'EXCHANGE:SYMBOL' strings e.g. ['NSE:RELIANCE', 'NSE:TCS']
        """
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_quotes", {"instruments": instruments})
        return await self._runner.run_async(cmd)

    async def get_ltp(self, instruments: list[str]) -> dict[str, Any]:
        """Fetch last traded price only (lighter than full quotes)."""
        from src.commands.kite_cmd import KiteToolCommand
        cmd = KiteToolCommand(self, "get_ltp", {"instruments": instruments})
        return await self._runner.run_async(cmd)
